permalink: /blog/:title
auto: true
markdown: kramdown
exclude: Rakefile, CNAME, sass/, script/, README.md

url: http://jayrambhia.com

name: "Jay Rambhia"
tagline: "Make computers see"
description: "Notes and codes of a paranoid android who wants track people"
about: "I'm <strong>Jay Rambhia</strong>. I'm interested in Computer Vision and Pattern Recognition. Currenlty I'm working on visual based tracking algorithms."
author:
 name: "Jay Rambhia"
 email: "jayrambhia777@gmail.com"
 github: "jayrambhia"
 twitter: "jayrambhia"
 facebook: "jay.rambhia"
